import "server-only";
import {
  type ReplayCompactionEvent,
  type ReplayData,
  type ReplayTurn,
  parseMcpTool,
} from "@control-plane/core";

import { loadReplay } from "@/lib/sessions-analytics";

/**
 * GET /sessions/:id/export
 *
 * Emits a single self-contained HTML file reflecting the full replay. Inline
 * CSS only — no remote JS, no external stylesheets — so the file opens in any
 * browser standalone (CCV-24). The markup is intentionally minimal; the goal
 * is a durable archive, not perfect parity with the live dashboard.
 */
export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
): Promise<Response> {
  const { id } = await params;
  const result = await loadReplay(id);
  if (!result.ok) {
    const status = result.reason === "unconfigured" ? 503 : 500;
    return new Response(`Replay unavailable: ${result.reason}`, { status });
  }
  if (!result.value) {
    return new Response(`Session not found: ${id}`, { status: 404 });
  }

  const html = renderExport(result.value);
  return new Response(html, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="session-${safeName(id)}.html"`,
      "Cache-Control": "no-store",
    },
  });
}

function safeName(input: string): string {
  return input.replace(/[^A-Za-z0-9._-]/g, "_").slice(0, 80);
}

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function formatTokens(n: number): string {
  if (!Number.isFinite(n)) return "—";
  const abs = Math.abs(n);
  if (abs < 1_000) return String(Math.trunc(abs));
  if (abs < 1_000_000) return `${(abs / 1_000).toFixed(1)}k`;
  if (abs < 1_000_000_000) return `${(abs / 1_000_000).toFixed(1)}M`;
  return `${(abs / 1_000_000_000).toFixed(1)}B`;
}

function formatCost(usd: number): string {
  if (!Number.isFinite(usd)) return "—";
  const abs = Math.abs(usd);
  if (abs === 0) return "$0.00";
  if (abs < 0.01) return `$${abs.toFixed(4)}`;
  if (abs < 1_000) return `$${abs.toFixed(2)}`;
  return `$${(abs / 1_000).toFixed(1)}k`;
}

function renderExport(replay: ReplayData): string {
  const compactionByTurn = new Map<number, ReplayCompactionEvent>();
  for (const c of replay.compactions) compactionByTurn.set(c.turnIndex, c);

  const assistantTurns = replay.turns.filter((t) => t.type === "assistant").length;
  let inputTokens = 0,
    outputTokens = 0,
    cacheRead = 0,
    cacheWrite = 0;
  for (const t of replay.turns) {
    if (!t.usage) continue;
    inputTokens += t.usage.inputTokens;
    outputTokens += t.usage.outputTokens;
    cacheRead += t.usage.cacheReadInputTokens;
    cacheWrite += t.usage.cacheCreationInputTokens;
  }
  const totalTokens = inputTokens + outputTokens + cacheRead + cacheWrite;

  const toolResults = new Map<string, { content: string; isError: boolean }>();
  for (const t of replay.turns) {
    if (!t.toolResults) continue;
    for (const r of t.toolResults)
      toolResults.set(r.toolUseId, { content: r.content, isError: r.isError });
  }

  const turnsHtml = replay.turns
    .map((turn, i) => renderTurn(turn, i, compactionByTurn.get(i), toolResults))
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Session ${escapeHtml(replay.sessionId)}</title>
<style>${CSS}</style>
</head>
<body>
<header>
  <p class="eyebrow">Session replay export</p>
  <h1>${escapeHtml(replay.slug ?? replay.sessionId)}</h1>
  <p class="meta">${escapeHtml(replay.sessionId)}</p>
  <dl class="stats">
    <div><dt>Assistant turns</dt><dd>${assistantTurns}</dd></div>
    <div><dt>Tokens</dt><dd>${formatTokens(totalTokens)}</dd></div>
    <div><dt>Cost</dt><dd>${formatCost(replay.totalCostUsd)}</dd></div>
    <div><dt>Compactions</dt><dd>${replay.compactions.length}</dd></div>
    ${replay.gitBranch ? `<div><dt>Branch</dt><dd>${escapeHtml(replay.gitBranch)}</dd></div>` : ""}
    ${replay.version ? `<div><dt>Version</dt><dd>v${escapeHtml(replay.version)}</dd></div>` : ""}
  </dl>
</header>
<main>${turnsHtml}</main>
<footer>
  <p>Generated by control-plane · self-contained HTML · no external resources</p>
</footer>
</body>
</html>`;
}

function renderTurn(
  turn: ReplayTurn,
  index: number,
  compactionBefore: ReplayCompactionEvent | undefined,
  toolResults: ReadonlyMap<string, { content: string; isError: boolean }>
): string {
  const parts: string[] = [];
  if (compactionBefore) {
    parts.push(
      `<div class="compaction"><strong>⚡ Context compaction</strong> · trigger ${escapeHtml(
        compactionBefore.trigger
      )} · ${formatTokens(compactionBefore.preTokens)} tokens before</div>`
    );
  }

  if (turn.type === "user") {
    parts.push('<section class="turn user">');
    parts.push(
      `<p class="eyebrow">User · ${escapeHtml(new Date(turn.timestamp).toISOString())}</p>`
    );
    if (turn.text)
      parts.push(`<div class="bubble user-bubble"><pre>${escapeHtml(turn.text)}</pre></div>`);
    if (turn.toolResults) {
      for (const r of turn.toolResults) {
        parts.push(
          `<div class="tool-result ${r.isError ? "error" : ""}"><pre>${escapeHtml(r.content).slice(0, 4000)}</pre></div>`
        );
      }
    }
    parts.push("</section>");
    return parts.join("");
  }

  parts.push('<section class="turn assistant">');
  parts.push(
    `<p class="eyebrow">Claude · ${escapeHtml(turn.model ?? "unknown")} · #${index + 1}</p>`
  );
  if (turn.hasThinking && turn.thinkingText) {
    parts.push(
      `<details class="thinking"><summary>Extended thinking</summary><pre>${escapeHtml(turn.thinkingText.slice(0, 6000))}</pre></details>`
    );
  }
  if (turn.toolCalls) {
    for (const tc of turn.toolCalls) {
      const result = toolResults.get(tc.id);
      const mcp = parseMcpTool(tc.name);
      const display = mcp ? `${mcp.server} · ${mcp.tool}` : tc.name;
      parts.push(
        `<div class="tool-call"><div class="tc-head"><strong>${escapeHtml(display)}</strong></div><pre>${escapeHtml(
          JSON.stringify(tc.input, null, 2).slice(0, 2000)
        )}</pre>${
          result
            ? `<div class="tc-result ${result.isError ? "error" : ""}"><pre>${escapeHtml(result.content.slice(0, 3000))}</pre></div>`
            : ""
        }</div>`
      );
    }
  }
  if (turn.text) {
    parts.push(`<div class="bubble assistant-bubble"><pre>${escapeHtml(turn.text)}</pre></div>`);
  }
  if (turn.usage) {
    const u = turn.usage;
    parts.push(
      `<p class="usage">in ${formatTokens(u.inputTokens)} · out ${formatTokens(u.outputTokens)} · cW ${formatTokens(
        u.cacheCreationInputTokens
      )} · cR ${formatTokens(u.cacheReadInputTokens)}${
        typeof turn.estimatedCostUsd === "number" ? ` · ${formatCost(turn.estimatedCostUsd)}` : ""
      }</p>`
    );
  }
  parts.push("</section>");
  return parts.join("");
}

// Inline CSS — dark theme, tailwind-equivalent. Kept small and self-contained.
const CSS = `
:root { color-scheme: dark; }
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  background: #0b0d12;
  color: #e5e7eb;
  line-height: 1.55;
  padding: 24px;
  max-width: 960px;
  margin: 0 auto;
}
header { border-bottom: 1px solid rgba(255,255,255,0.08); padding-bottom: 16px; margin-bottom: 24px; }
header h1 { margin: 4px 0; font-size: 22px; font-weight: 600; }
p.eyebrow { font-size: 10px; letter-spacing: 0.1em; text-transform: uppercase; color: #9aa1b4; margin: 0; }
p.meta { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 11px; color: #7a8194; margin: 4px 0 0; word-break: break-all; }
dl.stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px,1fr)); gap: 12px; margin-top: 16px; }
dl.stats div { background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.06); padding: 8px 12px; border-radius: 6px; }
dl.stats dt { font-size: 10px; color: #7a8194; text-transform: uppercase; letter-spacing: 0.08em; }
dl.stats dd { margin: 4px 0 0; font-size: 18px; font-weight: 600; color: #e5e7eb; font-variant-numeric: tabular-nums; }
section.turn { margin-bottom: 24px; padding: 12px; border: 1px solid rgba(255,255,255,0.06); border-radius: 8px; background: rgba(255,255,255,0.02); }
section.turn.user { background: rgba(52, 144, 248, 0.04); border-color: rgba(52, 144, 248, 0.15); }
.bubble pre { margin: 0; white-space: pre-wrap; word-break: break-word; font-family: inherit; font-size: 14px; }
.user-bubble { background: rgba(59, 130, 246, 0.08); border: 1px solid rgba(59,130,246,0.2); padding: 10px 12px; border-radius: 10px; }
.assistant-bubble { background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.08); padding: 10px 12px; border-radius: 10px; }
details.thinking { margin-top: 8px; background: rgba(99, 102, 241, 0.05); border: 1px solid rgba(99,102,241,0.2); border-radius: 6px; padding: 6px 10px; color: #c4b5fd; }
details.thinking pre { white-space: pre-wrap; font-size: 12px; margin: 6px 0 0; }
.tool-call { margin-top: 8px; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.06); border-radius: 6px; padding: 8px; }
.tool-call .tc-head { font-family: ui-monospace, monospace; font-size: 12px; color: #93c5fd; margin-bottom: 4px; }
.tool-call pre, .tool-result pre, .tc-result pre { white-space: pre-wrap; word-break: break-all; font-family: ui-monospace, monospace; font-size: 12px; background: rgba(0,0,0,0.25); padding: 8px; border-radius: 4px; margin: 0; max-height: 360px; overflow: auto; }
.tc-result, .tool-result { margin-top: 6px; }
.tc-result.error pre, .tool-result.error pre { background: rgba(239, 68, 68, 0.08); color: #fecaca; }
.compaction { background: rgba(245, 158, 11, 0.08); border: 1px solid rgba(245, 158, 11, 0.3); color: #fcd34d; padding: 10px 12px; border-radius: 8px; margin: 12px 0; font-size: 14px; }
.usage { margin: 8px 0 0; font-family: ui-monospace, monospace; font-size: 11px; color: #9aa1b4; }
footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid rgba(255,255,255,0.08); color: #7a8194; font-size: 11px; }
`;
